routes/web.php
    Route::prefix('suggestions')->group(function (){
        Route::get('','SuggestionsController@index')->name('suggestions.index');
        Route::get('/show/{id}','SuggestionsController@show')->name('suggestions.show');
        Route::post('/{id}','SuggestionsController@destroy')->name('suggestions.destroy');
    });

    Route::prefix('users')->group(function (){
        Route::get('','UsersController@index')->name('users.index');
        Route::get('/create','UsersController@create')->name('users.create');
        Route::post('/store','UsersController@store')->name('users.store');
        Route::get('/details/{id}','UsersController@show')->name('users.show');
        Route::get('/edit/{id}','UsersController@edit')->name('users.edit');
        Route::post('/update/{id}','UsersController@update')->name('user.edit.password');
        Route::post('/{id}','UsersController@destroy')->name('users.destroy');
        Route::post('/status/{id}', 'UsersController@updateStatus')->name('users.status');

    });


    Route::prefix('cities')->group(function (){
        Route::get('','CityController@index')->name('cities.index');
        Route::get('/create','CityController@create')->name('cities.create');
        Route::post('/store','CityController@store')->name('cities.store');
        Route::get('/edit/{id}','CityController@edit')->name('cities.edit');
        Route::post('/update/{id}','CityController@update')->name('cities.update');
        Route::post('/{id}','CityController@destroy')->name('cities.destroy');
        Route::post('/status/{id}', 'CityController@updateStatus')->name('cities.status');
    });

    Route::prefix('categories')->group(function (){
        Route::get('','CategoryController@index')->name('categories.index');
        Route::get('/create','CategoryController@create')->name('categories.create');
        Route::post('/store','CategoryController@store')->name('categories.store');
        Route::get('/edit/{id}','CategoryController@edit')->name('categories.edit');
        Route::post('/update/{id}','CategoryController@update')->name('categories.update');
        Route::post('/{id}','CategoryController@destroy')->name('categories.destroy');
        Route::post('/status/{id}', 'CategoryController@updateStatus')->name('categories.status');
    });

    Route::prefix('units')->group(function (){
        Route::get('','UnitController@index')->name('units.index');
        Route::get('/create','UnitController@create')->name('units.create');
        Route::post('/store','UnitController@store')->name('units.store');
        Route::get('/edit/{id}','UnitController@edit')->name('units.edit');
        Route::post('/update/{id}','UnitController@update')->name('units.update');
        Route::post('/{id}','UnitController@destroy')->name('units.destroy');
        Route::post('/status/{id}', 'UnitController@updateStatus')->name('units.status');
    });

    Route::prefix('subcategories')->group(function (){
        Route::get('','SubcategoryController@index')->name('subcategories.index');
        Route::get('/create','SubcategoryController@create')->name('subcategories.create');
        Route::post('/store','SubcategoryController@store')->name('subcategories.store');
        Route::get('/edit/{id}','SubcategoryController@edit')->name('subcategories.edit');
        Route::post('/update/{id}','SubcategoryController@update')->name('subcategories.update');
        Route::post('/{id}','SubcategoryController@destroy')->name('subcategories.destroy');
        Route::post('/status/{id}', 'SubcategoryController@updateStatus')->name('subcategories.status');
    });


    Route::prefix('packages')->group(function (){
        Route::get('','PackagesController@index')->name('packages.index');
        Route::get('/create','PackagesController@create')->name('packages.create');
        Route::post('/store','PackagesController@store')->name('packages.store');
        Route::get('/edit/{id}','PackagesController@edit')->name('packages.edit');
        Route::post('/update/{id}','PackagesController@update')->name('packages.update');
        Route::post('/{id}','PackagesController@destroy')->name('packages.destroy');
        Route::post('/status/{id}', 'PackagesController@updateStatus')->name('packages.status');
    });

    Route::prefix('subscriptions')->group(function (){
        Route::get('','SubscriptionsController@index')->name('subscriptions.index');
        Route::get('/create','SubscriptionsController@create')->name('subscriptions.create');
        Route::post('/store','SubscriptionsController@store')->name('subscriptions.store');
        Route::get('/edit/{id}','SubscriptionsController@edit')->name('subscriptions.edit');
        Route::post('/update/{id}','SubscriptionsController@update')->name('subscriptions.update');
        Route::post('/{id}','SubscriptionsController@destroy')->name('subscriptions.destroy');
        Route::post('/status/{id}', 'SubscriptionsController@updateStatus')->name('subscriptions.status');
    });

    Route::prefix('users')->group(function (){
        Route::get('','UsersController@index')->name('users.index');
        Route::get('/details/{id}','UsersController@show')->name('users.show');
        Route::post('/{id}','UsersController@destroy')->name('users.destroy');
        Route::post('/status/{id}', 'UsersController@updateStatus')->name('users.status');
    });

    Route::prefix('admins')->group(function (){
        Route::get('','AdminsController@index')->name('admins.index');
        Route::get('/create','AdminsController@create')->name('admins.create');
        Route::post('/store','AdminsController@store')->name('admins.store');
        Route::get('/edit/{id}','AdminsController@edit')->name('admins.edit');
        Route::post('/update/{id}','AdminsController@update')->name('admins.update');
        Route::post('/{id}','AdminsController@destroy')->name('admins.destroy');
        Route::post('/status/{id}', 'AdminsController@updateStatus')->name('admins.status');
    });

    Route::prefix('members')->group(function (){
        Route::get('','MembersController@index')->name('members.index');
        Route::get('/create','MembersController@create')->name('members.create');
        Route::post('/store','MembersController@store')->name('members.store');
        Route::get('/edit/{id}','MembersController@edit')->name('members.edit');
        Route::post('/update/{id}','MembersController@update')->name('members.update');
        Route::post('/{id}','MembersController@destroy')->name('members.destroy');
        Route::post('/status/{id}', 'MembersController@updateStatus')->name('members.status');
    });

    Route::prefix('technicians')->group(function (){
        Route::get('','TechniciansController@index')->name('technicians.index');
        Route::get('/create','TechniciansController@create')->name('technicians.create');
        Route::post('/store','TechniciansController@store')->name('technicians.store');
        Route::get('/edit/{id}','TechniciansController@edit')->name('technicians.edit');
        Route::post('/update/{id}','TechniciansController@update')->name('technicians.update');
        Route::post('/{id}','TechniciansController@destroy')->name('technicians.destroy');
        Route::post('/status/{id}', 'TechniciansController@updateStatus')->name('technicians.status');
        Route::post('/status/availability/{id}', 'TechniciansController@technicianAvailability')->name('technicians.availability');
        Route::get('/details/{id}','TechniciansController@show')->name('technicians.show');
    });

    Route::prefix('rates')->group(function (){
        Route::get('users','UsersRatesController@index')->name('users.rates.index');
        Route::get('users/show/{id}','UsersRatesController@show')->name('users.rates.show');
        Route::post('users/{id}','UsersRatesController@destroy')->name('users.rates.destroy');
    });

    Route::prefix('rates')->group(function (){
        Route::get('technicians','TechniciansRateController@index')->name('technicians.rates.index');
        Route::get('technicians/show/{id}','TechniciansRateController@show')->name('technicians.rates.show');
        Route::post('technicians/{id}','TechniciansRateController@destroy')->name('technicians.rates.destroy');
    });

    Route::prefix('subscriptions-users')->group(function (){
        Route::get('','UsersSubscriptionsController@index')->name('users.subscriptions.index');
        Route::get('/show/{id}','UsersSubscriptionsController@show')->name('users.subscriptions.show');
        Route::post('/{id}','UsersSubscriptionsController@destroy')->name('users.subscriptions.destroy');
        Route::post('/status/{id}', 'UsersSubscriptionsController@updateStatus')->name('users.subscriptions.status');
    });

    Route::prefix('orders')->group(function (){
        Route::get('','OrdersController@index')->name('orders.index');
        Route::get('/edit/{id}','OrdersController@edit')->name('orders.edit');
        Route::post('/update/{id}','OrdersController@update')->name('orders.update');
        Route::post('/{id}','OrdersController@destroy')->name('orders.destroy');
        Route::get('/details/{id}','OrdersController@show')->name('orders.show');
        Route::get('/invoice/{id}','OrdersController@generatePdf')->name('orders.invoice');

    });

    Route::resource('roles','RoleController');
    Route::post('/roles/destroy/{id}', 'RoleController@destroy')->name('roles.destroy');

    Route::resource('staffs','StaffController');
    Route::post('/staffs/destroy/{id}', 'StaffController@destroy')->name('staffs.destroy');

    Route::prefix('notifications')->group(function (){
        Route::get('','NotificationsController@index')->name('notifications.index');
        Route::get('/create','NotificationsController@create')->name('notifications.create');
        Route::post('/store','NotificationsController@store')->name('notifications.store');

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    protected $table='staffs';
    protected $fillable=['user_id', 'role_id'];

  public function user(){
    return $this->belongsTo(User::class);
  }

  public function role(){
    return $this->belongsTo(Role::class);
  }

}

app/Http/Controllers/Dashboard/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use Illuminate\Http\Request;
use App\Staff;
use App\Role;
use App\User;
use Hash;
use App\Http\Controllers\Controller;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $staffs = Staff::all();
        return view('dashboard.views.staffs.index', compact('staffs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('dashboard.views.staffs.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->user_type = "staff";
        $user->password = $request->password;
        if($user->save()){
            $staff = new Staff;
            $staff->user_id = $user->id;
            $staff->role_id = $request->role_id;
            if($staff->save()){
                return redirect()->route('staffs.index')->with('successMsg','Staff has been inserted successfully');

            }
        }

        return redirect()->back()->with('errorMsg','Something went wrong');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $staff = Staff::findOrFail(decrypt($id));
        $roles = Role::all();
        return view('dashboard.views.staffs.edit', compact('staff', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $staff = Staff::findOrFail($id);
        $user = $staff->user;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password =$request->password;
        $staff->role_id = $request->role_id;
        if($user->save()){
                return redirect()->route('staffs.index')->with('successMsg','Staff has been updated successfully');

        }

//        flash(__('Something went wrong'))->error();
//        return back();
        return redirect()->back()->with('errorMsg','Something went wrong');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy(Staff::findOrFail($id)->user->id);
        if(Staff::destroy($id)){
//            flash(__('Staff has been deleted successfully'))->success();
//            return redirect()->route('staffs.index');
            return redirect()->route('staffs.index')->with('successMsg','Staff has been deleted successfully');

        }

        return redirect()->back()->with('errorMsg','Something went wrong');
    }
}

resources/views/dashboard/views/staffs/create.blade.php
{{--@extends('dashboard.layouts.master')--}}

{{--@section('content')--}}

{{--<div class="col-lg-6 col-lg-offset-3">--}}
{{--    <div class="panel">--}}
{{--        <div class="panel-heading">--}}
{{--            <h3 class="panel-title">{{__('Staff Information')}}</h3>--}}
{{--        </div>--}}

{{--        <!--Horizontal Form-->--}}
{{--        <!--===================================================-->--}}
{{--        <form class="form-horizontal" action="{{ route('staffs.store') }}" method="POST" enctype="multipart/form-data">--}}
{{--        	@csrf--}}
{{--            <div class="panel-body">--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="name">{{__('Name')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <input type="text" placeholder="{{__('Name')}}" id="name" name="name" class="form-control" required>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="email">{{__('Email')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <input type="text" placeholder="{{__('Email')}}" id="email" name="email" class="form-control" required>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="password">{{__('Password')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <input type="password" placeholder="{{__('Password')}}" id="password" name="password" class="form-control" required>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="name">{{__('Role')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <select name="role_id" required class="form-control demo-select2-placeholder">--}}
{{--                            @foreach($roles as $role)--}}
{{--                                <option value="{{$role->id}}">{{$role->name}}</option>--}}
{{--                            @endforeach--}}
{{--                        </select>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <div class="panel-footer text-right">--}}
{{--                <button class="btn btn-purple" type="submit">{{__('Save')}}</button>--}}
{{--            </div>--}}
{{--        </form>--}}
{{--        <!--===================================================-->--}}
{{--        <!--End Horizontal Form-->--}}

{{--    </div>--}}
{{--</div>--}}

{{--@endsection--}}




@extends('dashboard.layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-left">
                            <h3>{{trans('staff.Add Staff')}}</h3>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">{{trans('staff.staffs')}}</li>
                                <li class="breadcrumb-item active">{{trans('staff.Add Staff')}}</li>
                            </ol>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h5>{{trans('category.completeform')}}</h5>
                        </div>
                        <div class="card-body">
                            <form class="needs-validation" novalidate="" action="{{ route('staffs.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="col-md-12">
                                    <div class="form-group mb-0">
                                        <label class="form-label">{{trans('user.name')}}</label>
                                        <input class="form-control" id="name" name="name" placeholder="name"/>
                                    </div>
                                </div>
                                <br>
                                <div class="col-md-12">
                                    <div class="form-group mb-0">
                                        <label class="form-label">{{trans('user.email')}}</label>
                                        <input class="form-control" id="email" name="email"  placeholder="email"/>
                                    </div>
                                </div>
                                <br>

                                <div class="col-md-12">
                                    <div class="form-group mb-0">
                                        <label for="exampleFormControlTextarea4">{{trans('user.password')}}</label>
                                        <input class="form-control" id="Password" name="Password"  placeholder="Password"/>
                                    </div>
                                </div>
                                <br>
                                <div class="col-md-12">
                                    <div class="col-form-label">{{trans('staff.Role')}}</div>
                                    <select name="role_id" class="js-example-placeholder-multiple col-sm-12" multiple="multiple">
                                        @foreach($roles as $role)
                                            <option value="{{$role->id}}">{{$role->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <br>
                                <button class="btn btn-primary" type="submit">{{trans('user.submit')}}</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>
@endsection

resources/views/dashboard/views/staffs/edit.blade.php
{{--@extends('dashboard.layouts.master')--}}

{{--@section('content')--}}

{{--<div class="col-lg-6 col-lg-offset-3">--}}
{{--    <div class="panel">--}}
{{--        <div class="panel-heading">--}}
{{--            <h3 class="panel-title">{{__('Staff Information')}}</h3>--}}
{{--        </div>--}}

{{--        <!--Horizontal Form-->--}}
{{--        <!--===================================================-->--}}
{{--        <form class="form-horizontal" action="{{ route('staffs.store') }}" method="POST" enctype="multipart/form-data">--}}
{{--        	@csrf--}}
{{--            <div class="panel-body">--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="name">{{__('Name')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <input type="text" placeholder="{{__('Name')}}" id="name" name="name" class="form-control" required>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="email">{{__('Email')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <input type="text" placeholder="{{__('Email')}}" id="email" name="email" class="form-control" required>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="password">{{__('Password')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <input type="password" placeholder="{{__('Password')}}" id="password" name="password" class="form-control" required>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="form-group">--}}
{{--                    <label class="col-sm-3 control-label" for="name">{{__('Role')}}</label>--}}
{{--                    <div class="col-sm-9">--}}
{{--                        <select name="role_id" required class="form-control demo-select2-placeholder">--}}
{{--                            @foreach($roles as $role)--}}
{{--                                <option value="{{$role->id}}">{{$role->name}}</option>--}}
{{--                            @endforeach--}}
{{--                        </select>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <div class="panel-footer text-right">--}}
{{--                <button class="btn btn-purple" type="submit">{{__('Save')}}</button>--}}
{{--            </div>--}}
{{--        </form>--}}
{{--        <!--===================================================-->--}}
{{--        <!--End Horizontal Form-->--}}

{{--    </div>--}}
{{--</div>--}}

{{--@endsection--}}




@extends('dashboard.layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-left">
                            <h3>{{trans('staff.Edit Staff')}}</h3>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">{{trans('staff.staffs')}}</li>
                                <li class="breadcrumb-item active">{{trans('staff.Edit Staff')}}</li>
                            </ol>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h5>{{trans('category.completeform')}}</h5>
                        </div>
                        <div class="card-body">
                            <form class="needs-validation" novalidate="" action="{{ route('staffs.update', $staff->id) }}" method="POST" enctype="multipart/form-data">
                                <input name="_method" type="hidden" value="PATCH">
                                @csrf
                                <div class="col-md-12">
                                    <div class="form-group mb-0">
                                        <label class="form-label">{{trans('user.name')}}</label>
                                        <input class="form-control" value="{{ $staff->user->name }}" id="name" name="name" placeholder="name"/>
                                    </div>
                                </div>
                                <br>
                                <div class="col-md-12">
                                    <div class="form-group mb-0">
                                        <label class="form-label">{{trans('user.email')}}</label>
                                        <input class="form-control" value="{{ $staff->user->email }}" id="email" name="email"  placeholder="email"/>
                                    </div>
                                </div>
                                <br>

                                <div class="col-md-12">
                                    <div class="form-group mb-0">
                                        <label for="exampleFormControlTextarea4">{{trans('user.password')}}</label>
                                        <input class="form-control" id="Password" name="Password"  placeholder="Password"/>
                                    </div>
                                </div>
                                <br>
                                <div class="col-md-12">
                                    <div class="col-form-label">{{trans('staff.Role')}}</div>
                                    <select name="role_id" required class="form-control demo-select2-placeholder">
                                        @foreach($roles as $role)
                                            <option value="{{$role->id}}" @php if($staff->role_id == $role->id) echo "selected"; @endphp >{{$role->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <br>
                                <button class="btn btn-primary" type="submit">{{trans('user.submit')}}</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>
@endsection