routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/get-category-units/{category_id}', 'Dashboard\Admin\CategoryController@getCategoryUnits');

Route::get('/get-subcategory-units/{unit_id}', 'Dashboard\Admin\CategoryController@getSubcategoriesUnit');

Route::get('/', function () {
    return view('welcome');
});


//Route::get('/login', function () {
//    return view('login');
//});
//
//Route::get('/dashboard', function () {
//    return view('dashboard');
//});



Route::group(['prefix'=>'admin','namespace'=>'Dashboard\Auth'], function (){
    Route::group(['prefix'=>'login'],function () {
        Route::get('', 'AuthenticationController@index')->name('login');
        Route::post('auth', 'AuthenticationController@login')->name('user.login');
        Route::get('/show/{id}','SuggestionsController@show')->name('suggestion.show');
        Route::get('/show/{id}','OrdersController@show')->name('order.show');
    });
});

Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'Dashboard\Admin'], function () {
    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/home', 'DashboardController@index')->name('dashboard');
        Route::post('', 'DashboardController@logout')->name('logout');
        Route::get('/backup','DashboardController@backup')->name('backup');
    });

    Route::group(['prefix' => 'profile'], function () {
        Route::get('', 'ProfileController@index')->name('profile');
        Route::post('/update/{id}','ProfileController@update')->name('profile.update');
    });

    Route::group(['prefix' => 'settings'], function () {
        Route::get('', 'SettingsController@index')->name('settings');
        Route::post('/update','SettingsController@update')->name('settings.update');
    });

    Route::prefix('suggestions')->group(function (){
        Route::get('','SuggestionsController@index')->name('suggestions.index');
        Route::get('/show/{id}','SuggestionsController@show')->name('suggestions.show');
        Route::post('/{id}','SuggestionsController@destroy')->name('suggestions.destroy');
    });

    Route::prefix('users')->group(function (){
        Route::get('','UsersController@index')->name('users.index');
        Route::get('/create','UsersController@create')->name('users.create');
        Route::post('/store','UsersController@store')->name('users.store');
        Route::get('/details/{id}','UsersController@show')->name('users.show');
        Route::get('/edit/{id}','UsersController@edit')->name('users.edit');
        Route::post('/update/{id}','UsersController@update')->name('user.edit.password');
        Route::post('/{id}','UsersController@destroy')->name('users.destroy');
        Route::post('/status/{id}', 'UsersController@updateStatus')->name('users.status');

    });


    Route::prefix('cities')->group(function (){
        Route::get('','CityController@index')->name('cities.index');
        Route::get('/create','CityController@create')->name('cities.create');
        Route::post('/store','CityController@store')->name('cities.store');
        Route::get('/edit/{id}','CityController@edit')->name('cities.edit');
        Route::post('/update/{id}','CityController@update')->name('cities.update');
        Route::post('/{id}','CityController@destroy')->name('cities.destroy');
        Route::post('/status/{id}', 'CityController@updateStatus')->name('cities.status');
    });

    Route::prefix('categories')->group(function (){
        Route::get('','CategoryController@index')->name('categories.index');
        Route::get('/create','CategoryController@create')->name('categories.create');
        Route::post('/store','CategoryController@store')->name('categories.store');
        Route::get('/edit/{id}','CategoryController@edit')->name('categories.edit');
        Route::post('/update/{id}','CategoryController@update')->name('categories.update');
        Route::post('/{id}','CategoryController@destroy')->name('categories.destroy');
        Route::post('/status/{id}', 'CategoryController@updateStatus')->name('categories.status');
    });

    Route::prefix('units')->group(function (){
        Route::get('','UnitController@index')->name('units.index');
        Route::get('/create','UnitController@create')->name('units.create');
        Route::post('/store','UnitController@store')->name('units.store');
        Route::get('/edit/{id}','UnitController@edit')->name('units.edit');
        Route::post('/update/{id}','UnitController@update')->name('units.update');
        Route::post('/{id}','UnitController@destroy')->name('units.destroy');
        Route::post('/status/{id}', 'UnitController@updateStatus')->name('units.status');
    });

    Route::prefix('subcategories')->group(function (){
        Route::get('','SubcategoryController@index')->name('subcategories.index');
        Route::get('/create','SubcategoryController@create')->name('subcategories.create');
        Route::post('/store','SubcategoryController@store')->name('subcategories.store');
        Route::get('/edit/{id}','SubcategoryController@edit')->name('subcategories.edit');
        Route::post('/update/{id}','SubcategoryController@update')->name('subcategories.update');
        Route::post('/{id}','SubcategoryController@destroy')->name('subcategories.destroy');
        Route::post('/status/{id}', 'SubcategoryController@updateStatus')->name('subcategories.status');
    });


    Route::prefix('packages')->group(function (){
        Route::get('','PackagesController@index')->name('packages.index');
        Route::get('/create','PackagesController@create')->name('packages.create');
        Route::post('/store','PackagesController@store')->name('packages.store');
        Route::get('/edit/{id}','PackagesController@edit')->name('packages.edit');
        Route::post('/update/{id}','PackagesController@update')->name('packages.update');
        Route::post('/{id}','PackagesController@destroy')->name('packages.destroy');
        Route::post('/status/{id}', 'PackagesController@updateStatus')->name('packages.status');
    });

    Route::prefix('subscriptions')->group(function (){
        Route::get('','SubscriptionsController@index')->name('subscriptions.index');
        Route::get('/create','SubscriptionsController@create')->name('subscriptions.create');
        Route::post('/store','SubscriptionsController@store')->name('subscriptions.store');
        Route::get('/edit/{id}','SubscriptionsController@edit')->name('subscriptions.edit');
        Route::post('/update/{id}','SubscriptionsController@update')->name('subscriptions.update');
        Route::post('/{id}','SubscriptionsController@destroy')->name('subscriptions.destroy');
        Route::post('/status/{id}', 'SubscriptionsController@updateStatus')->name('subscriptions.status');
    });

    Route::prefix('users')->group(function (){
        Route::get('','UsersController@index')->name('users.index');
        Route::get('/details/{id}','UsersController@show')->name('users.show');
        Route::post('/{id}','UsersController@destroy')->name('users.destroy');
        Route::post('/status/{id}', 'UsersController@updateStatus')->name('users.status');
    });

    Route::prefix('admins')->group(function (){
        Route::get('','AdminsController@index')->name('admins.index');
        Route::get('/create','AdminsController@create')->name('admins.create');
        Route::post('/store','AdminsController@store')->name('admins.store');
        Route::get('/edit/{id}','AdminsController@edit')->name('admins.edit');
        Route::post('/update/{id}','AdminsController@update')->name('admins.update');
        Route::post('/{id}','AdminsController@destroy')->name('admins.destroy');
        Route::post('/status/{id}', 'AdminsController@updateStatus')->name('admins.status');
    });

    Route::prefix('members')->group(function (){
        Route::get('','MembersController@index')->name('members.index');
        Route::get('/create','MembersController@create')->name('members.create');
        Route::post('/store','MembersController@store')->name('members.store');
        Route::get('/edit/{id}','MembersController@edit')->name('members.edit');
        Route::post('/update/{id}','MembersController@update')->name('members.update');
        Route::post('/{id}','MembersController@destroy')->name('members.destroy');
        Route::post('/status/{id}', 'MembersController@updateStatus')->name('members.status');
    });

    Route::prefix('technicians')->group(function (){
        Route::get('','TechniciansController@index')->name('technicians.index');
        Route::get('/create','TechniciansController@create')->name('technicians.create');
        Route::post('/store','TechniciansController@store')->name('technicians.store');
        Route::get('/edit/{id}','TechniciansController@edit')->name('technicians.edit');
        Route::post('/update/{id}','TechniciansController@update')->name('technicians.update');
        Route::post('/{id}','TechniciansController@destroy')->name('technicians.destroy');
        Route::post('/status/{id}', 'TechniciansController@updateStatus')->name('technicians.status');
        Route::post('/status/availability/{id}', 'TechniciansController@technicianAvailability')->name('technicians.availability');
        Route::get('/details/{id}','TechniciansController@show')->name('technicians.show');
    });

    Route::prefix('rates')->group(function (){
        Route::get('users','UsersRatesController@index')->name('users.rates.index');
        Route::get('users/show/{id}','UsersRatesController@show')->name('users.rates.show');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    protected $table='users';

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone','address', 'lat', 'lng', 'social_type', 'social_token',
        'jwt_token','firebase_token','user_status', 'status','verify_code', 'user_type','image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    public function setImageAttribute($value)
    {
        if ($value)
        {
            $imageName=time().'.'.$value->getClientOriginalExtension();
            $value->move(public_path('uploads/user/profile/'),$imageName);
            $this->attributes['image']=$imageName;
        }
    }
    public function getImageAttribute($value)
    {
        if ($value) {
            return asset('uploads/user/profile/'.$value);
        } else {
            return asset('uploads/user/profile/default.png');
        }
    }
    public function setPasswordAttribute($password)
    {
        return $this->attributes['password'] = bcrypt($password);
    }

      public function technicians()
    {
        return $this->hasMany('App\Technician');
    }

      public function rateTechnicians()
    {
        return $this->hasMany('App\RateTechnician');
    }

      public function subcategories()
    {
        return $this->hasMany('App\Subcategory');
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->toDateString();
    }

    public function subscription()
    {
        return $this->belongsTo('App\Subscription','subscription_id');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function package()
    {
        return $this->belongsTo('App\Package');
    }

    public function city()
    {
        return $this->belongsTo('App\City','city_id');
    }
}

app/Http/Controllers/Dashboard/Admin/SuggestionsController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use App\Contact;
use App\Suggestion;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SuggestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suggestions=Contact::all();
        return view('dashboard.views.suggestions.index',compact('suggestions'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $suggestion = Contact::find($id);
        $suggestion->view = 1;
        $suggestion->save();
        return view('dashboard.views.suggestions.show',compact('suggestion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $suggestion = Contact::find($id);
        $suggestion->delete();
        return redirect()->back()->with('successMsg','Suggestion Successfully Delete');
    }
}

resources/views/dashboard/views/suggestions/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-left">
                            <h3>{{trans('suggestion.suggestionsTable')}}</h3>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">{{trans('suggestion.suggestions')}}</li>
                                <li class="breadcrumb-item active">{{trans('suggestion.suggestionsTable')}}</li>
                            </ol>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <!-- Zero Configuration  Starts-->
                <div class="col-sm-12">
                    @include('dashboard.layouts.msg')
                    <div class="card">
                        <div class="card-header">
                            <h5>{{trans('suggestion.suggestionsTable')}} </h5>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="display" id="basic-1">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{trans('suggestion.Name')}}</th>
                                        <th>{{trans('suggestion.email')}}</th>
                                        <th>{{trans('suggestion.suggestion')}}</th>
                                        <th>{{trans('suggestion.CreatedAt')}}</th>
                                        <th>{{trans('suggestion.actions')}}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($suggestions as $key=>$suggestion)
                                        <tr>
                                            <td>{{ $key + 1 }}</td>
                                            <td>{{$suggestion->user->name}}</td>
                                            <td>{{$suggestion->user->email}}</td>
                                            <td>{{$suggestion->problem}}</td>
                                            <td>{{$suggestion->created_at}}</td>
                                            <td>
                                                <a href="{{ route('suggestions.show',$suggestion->id) }}" class="btn btn-info">{{trans('admin.details')}}</a>

                                                <form id="delete-form-{{ $suggestion->id }}" action="{{ route('suggestions.destroy',$suggestion->id) }}" style="display: none;" method="POST">
                                                    @csrf
                                                </form>
                                                <button type="button" class="btn btn-danger" onclick="if(confirm('{{trans('admin.deletemsg')}}')){
                                                        event.preventDefault();
                                                        document.getElementById('delete-form-{{ $suggestion->id }}').submit();
                                                        }else {
                                                        event.preventDefault();
                                                        }">{{trans('admin.delete')}}</button>
                                            </td>
                                        </tr>
                                    @endforeach


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Zero Configuration  Ends-->
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>





@endsection

resources/views/dashboard/views/suggestions/show.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-left">
                            <h3>{{trans('suggestion.read')}}</h3>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">{{trans('suggestion.suggestions')}}  </li>
                                <li class="breadcrumb-item active">{{trans('suggestion.read')}}</li>
                            </ol>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="email-wrap">
                <div class="row">


                    <div class="col-xl-12 col-md-12">
                        <div class="email-right-aside">
                            <div class="card email-body radius-left">
                                <div class="pl-0">
                                    <div class="tab-content">
                                        <div class="tab-pane fade" id="pills-darkhome" role="tabpanel" aria-labelledby="pills-darkhome-tab">
                                            <div class="email-compose">
                                                <div class="email-top compose-border">
                                                    <div class="row">
                                                        <div class="col-sm-8 xl-50">
                                                            <h4 class="mb-0">{{trans('suggestion.newmessage')}}</h4>
                                                        </div>
                                                        <div class="col-sm-4 btn-middle xl-50">
                                                            <button class="btn btn-primary btn-block btn-mail text-center mb-0 mt-0" type="button"><i class="fa fa-paper-plane mr-2"></i> SEND</button>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="email-wrapper">
                                                    <form class="theme-form">
                                                        <div class="form-group">
                                                            <label class="col-form-label pt-0" for="exampleInputEmail1">To</label>
                                                            <input class="form-control" id="exampleInputEmail1" type="email">
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="exampleInputPassword1">Subject</label>
                                                            <input class="form-control" id="exampleInputPassword1" type="text">
                                                        </div>
                                                        <div class="form-group mb-0">
                                                            <label class="text-muted">Message</label>
                                                            <textarea id="text-box" name="text-box" cols="10" rows="2">                                                            </textarea>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade active show" id="pills-darkprofile" role="tabpanel" aria-labelledby="pills-darkprofile-tab">
                                            <div class="email-content">
                                                <div class="email-top">
                                                    <div class="row">
                                                        <div class="col-md-6 xl-100 col-sm-12">
                                                            <div class="media"><img class="mr-3 rounded-circle" src="../assets/images/user/user.png" alt="">
                                                                <div class="media-body">
                                                                    <h6>
                                                                        <img alt="" width="100px" src="{{$suggestion->user->image}}" class="media-object thumb-sm img-circle">
                                                                        <br>
                                                                        <small><span class="digits">{{$suggestion->user->name}} <span class="digits">
                                                                                    <br> {{$suggestion->created_at}}</span></span></small></h6>
                                                                    <p>{{$suggestion->user->email}}</p>
                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                                <div class="email-wrapper">
                                                    <p>{{$suggestion->problem}}</p>
                                                </div>

                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <div class="text-right">
                                                            <a style="
    margin-right: 20px;
" href="{{route('suggestions.index')}}" type="button" class="btn btn-primary waves-effect waves-light w-md m-b-30"><i class="mdi mdi-reply m-r-10"></i>{{trans('suggestion.back')}}</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>
@endsection